// cliente.model.ts

export type TipoCliente = 'Recorrente' | 'Pontual';

/** Cliente as stored in Firestore. `id` is the Smart ID (e.g. "CLI-2609-001"). */
export interface Cliente {
  id: string;
  nome: string;
  email: string;
  telefone: string;
  cidade: string;
  bairro: string;
  rua: string;
  tipo: TipoCliente;
  observacoes: string;
  criadoEm?: number;   // Date.now() — optional but useful for sorting
}

/** Payload for creating a cliente (id is generated by the service). */
export type NovoCliente = Omit<Cliente, 'id'>;